services:
  writing_prompts_backend:
    build:
      context: writingprompts/backend
      dockerfile: Dockerfile
    container_name: writing_prompts_backend
    volumes:
      - ./writingprompts/backend/src:/app/src
    env_file: "writingprompts/backend/.env"
    ports:
      - "8000:8000"
  writing_prompts_frontend:
    build:
      context: writingprompts/frontend
      dockerfile: Dockerfile
    container_name: writing_prompts_frontend
    volumes:
      - ./writingprompts/frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - writing_prompts_backend
      - writing_prompts_frontend