services:
  backend:
    build:
      dockerfile: backend/Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: backend/src
          target: /code
    env_file: "backend/.env"
    ports:
      - "8000:8000"