services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/src:/app/src
    env_file: "backend/.env"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend