name: ESLint

on:
  push:
    paths:
      - home-app/src/**
      - writingprompts/frontend/src/**

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install home-app packages
        working-directory: ./home-app
        run: npm install
      - name: Run ESLint on home-app
        working-directory: ./home-app
        run: npm run githublint
      - name: Install writingprompts packages
        working-directory: ./writingprompts/frontend
        run: npm install
      - name: Run ESLint on writingprompts
        working-directory: ./writingprompts/frontend
        run: npm run githublint