name: 'Pytest'

on:
  push:
    paths:
      - writingprompts/backend/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./writingprompts/backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest