name: 'Vitest'

on:
  push:
    paths:
      - writingprompts/frontend/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./writingprompts/frontend

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 'Install Deps'
        run: npm install
      - name: 'Test'
        run: npx vitest